# ==================== 1. 应用核心配置 ====================
spring:
  application:
    name: partner-service-backend
#  profiles:
#    active: prod


  # ==================== 2. 数据源配置 (SQL) ====================
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/partner_service_db
    username: root
    password: ${MYSQLDB_PASSWORD} # IDEA的环境变量


  # ==================== 3. 数据源配置 (NoSQL - Redis) ====================
  data:
    redis:
      host: localhost # 【重要】你缺少这个必填项！
      port: 6379      # 端口最好明确写出，即使用的是默认端口
      # password: 如果你的Redis有密码，在这里配置
      database: 0


#  # ==================== 4. Session 配置 ====================
#  session:
#    timeout: 86400 # session 失效时间


# ==================== 5. Web服务器配置 ====================
server:
  port: 8080
  # servlet:
  #   context-path: /api


# ==================== 6. 日志配置 ====================
#logging:
#  level:
#    root: info
#    com.zjl.partnerservice: debug  # 你的包路径日志级别
#  file:
#    name: logs/application.log  # 输出到文件
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
#    file: "%d{yyyy-MM-dd} [%thread] %-5level %logger{36} - %msg%n"


# ==================== 7. 第三方框架配置 (MyBatis-Plus) ====================
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #开启sql日志
    map-underscore-to-camel-case: true  # 自动转换驼峰命名
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除字段名
      logic-delete-value: 1 # 逻辑已删除值。可选，默认值为 1
      logic-not-delete-value: 0 # 逻辑未删除值。可选，默认值为 0


# ==================== 8. 第三方框架配置 (SpringDoc - Swagger) ====================
springdoc:
  api-docs:
    path: /api-docs  # OpenAPI JSON 路径
  swagger-ui:
    path: /swagger-ui.html  # 文档界面路径
    enabled: true
  show-actuator: false  # 是否显示actuator端点